class AyazRajpar:

        name = "Ayaz"
        Lastname = "Rajpar"
        fullname = "Ayaz Rajpar"
        Usertype = "Premium"
        Profilepic = "img/pics/image.jpg"
        massge1 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        massge2 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        massge3 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        massge4 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        massge5 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        massge6 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        massge7 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        massge8 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        massge9 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        massge10 = "Welcome Mr Ayaz Ali Rajpar , How Are u ..??"
        Notifacation1 = "This is FIrst Notification"
        Notifacation2 = "This is Second Notification"
        Notifacation3 = "This is third Notification"
        Notifacation4 = "This is fourth Notification"
        Notifacation5 = "This is Fifthe Notification"
        Notifacation6 = "This is Sixth Notification"
        Notifacation7 = "This is Seventh Notification"
        Notifacation8 = "This is 8th Notification"
        Notifacation10 = "This is 10th Notification"
    